/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AndroidRouteImport } from './routes/android'
import { Route as AparelhosRouteImport } from './routes/aparelhos'
import { Route as AppleRouteImport } from './routes/apple'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as OrdensIndexRouteImport } from './routes/ordens.index'
import { Route as OrdensIdRouteImport } from './routes/ordens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidRoute = AndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => rootRouteImport,
} as any)
const AparelhosRoute = AparelhosRouteImport.update({
  id: '/aparelhos',
  path: '/aparelhos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppleRoute = AppleRouteImport.update({
  id: '/apple',
  path: '/apple',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensIndexRoute = OrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensIdRoute = OrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/android': typeof AndroidRoute
  '/aparelhos': typeof AparelhosRoute
  '/apple': typeof AppleRoute
  '/clientes': typeof ClientesRoute
  '/ordens/$id': typeof OrdensIdRoute
  '/ordens/': typeof OrdensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/android': typeof AndroidRoute
  '/aparelhos': typeof AparelhosRoute
  '/apple': typeof AppleRoute
  '/clientes': typeof ClientesRoute
  '/ordens/$id': typeof OrdensIdRoute
  '/ordens': typeof OrdensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/android': typeof AndroidRoute
  '/aparelhos': typeof AparelhosRoute
  '/apple': typeof AppleRoute
  '/clientes': typeof ClientesRoute
  '/ordens/$id': typeof OrdensIdRoute
  '/ordens/': typeof OrdensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/android'
    | '/aparelhos'
    | '/apple'
    | '/clientes'
    | '/ordens/$id'
    | '/ordens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/android'
    | '/aparelhos'
    | '/apple'
    | '/clientes'
    | '/ordens/$id'
    | '/ordens'
  id:
    | '__root__'
    | '/'
    | '/android'
    | '/aparelhos'
    | '/apple'
    | '/clientes'
    | '/ordens/$id'
    | '/ordens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AndroidRoute: typeof AndroidRoute
  AparelhosRoute: typeof AparelhosRoute
  AppleRoute: typeof AppleRoute
  ClientesRoute: typeof ClientesRoute
  OrdensIdRoute: typeof OrdensIdRoute
  OrdensIndexRoute: typeof OrdensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android': {
      id: '/android'
      path: '/android'
      fullPath: '/android'
      preLoaderRoute: typeof AndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aparelhos': {
      id: '/aparelhos'
      path: '/aparelhos'
      fullPath: '/aparelhos'
      preLoaderRoute: typeof AparelhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apple': {
      id: '/apple'
      path: '/apple'
      fullPath: '/apple'
      preLoaderRoute: typeof AppleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens/': {
      id: '/ordens/'
      path: '/ordens'
      fullPath: '/ordens/'
      preLoaderRoute: typeof OrdensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens/$id': {
      id: '/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof OrdensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AndroidRoute: AndroidRoute,
  AparelhosRoute: AparelhosRoute,
  AppleRoute: AppleRoute,
  ClientesRoute: ClientesRoute,
  OrdensIdRoute: OrdensIdRoute,
  OrdensIndexRoute: OrdensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
