/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdensIndexRouteImport } from './routes/ordens.index'
import { Route as OrdensIdRouteImport } from './routes/ordens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensIndexRoute = OrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensIdRoute = OrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ordens/$id': typeof OrdensIdRoute
  '/ordens/': typeof OrdensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ordens/$id': typeof OrdensIdRoute
  '/ordens': typeof OrdensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ordens/$id': typeof OrdensIdRoute
  '/ordens/': typeof OrdensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ordens/$id' | '/ordens/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ordens/$id' | '/ordens'
  id: '__root__' | '/' | '/ordens/$id' | '/ordens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrdensIdRoute: typeof OrdensIdRoute
  OrdensIndexRoute: typeof OrdensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens/': {
      id: '/ordens/'
      path: '/ordens'
      fullPath: '/ordens/'
      preLoaderRoute: typeof OrdensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens/$id': {
      id: '/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof OrdensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrdensIdRoute: OrdensIdRoute,
  OrdensIndexRoute: OrdensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
